name: AnimeTalk
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.24.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.2
  path: ^1.8.3
  cached_network_image: ^3.3.0
  http: ^1.3.0
  get_it: ^7.6.7
  provider: ^6.0.0
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  jailbreak_root_detection: ^1.1.5
  dio: ^5.8.0+1
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.8.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
